### ISSUE TITLE
BuildAllGraphData task does not exist in build_graphs.py

### ISSUE THREAD

**Issue by titaniumrain** [macks22/dblp#13]
According to the documentation, there should be a task called BuillAllGraphData to build all the graphs, unfortunately, it does not exist in the code?

Thanks.

**Comment by macks22** [comment]
@titaniumrain thank you for the feedback; I have added the missing task and ensured it works as expected. You should now be able to build all the graph data by running `python pipeline/build_graphs.py BuildAllGraphData --start 2000 --end 2005 --local-scheduler --workers 4`.
