### ISSUE TITLE
python filtering.py FilterAllCSVRecordsToYearRange --start 1990 --end 2000 --local-scheduler does not work as guided

### ISSUE THREAD

**Issue by titaniumrain** [macks22/dblp#14]
Hi Mack,

Thanks for closing the BuildAllGraph issue so promptly. 

I also noticed that module 2 does not work as expected.

If I ran,

$ **python filtering.py FilterAllCSVRecordsToYearRange --start 1990 --end 2000 --local-scheduler**

I would receive the following errors.

ERROR: [pid 31790] Worker Worker(salt=969812214, workers=1, host=ubuntu, username=hello, pid=31790) failed    FilterVenuesToYearRange(start=1990, end=1990)
Traceback (most recent call last):
  File "/Users/hello/anaconda2/lib/python2.7/site-packages/luigi/worker.py", line 192, in run
    new_deps = self._run_get_new_deps()
  File "/Users/hello/anaconda2/lib/python2.7/site-packages/luigi/worker.py", line 130, in _run_get_new_deps
    task_gen = self.task.run()
  File "filtering.py", line 158, in run
    with self.output().open() as afile:
  File "/Users/hello/anaconda2/lib/python2.7/site-packages/luigi/local_target.py", line 152, in open
    fileobj = FileWrapper(io.BufferedReader(io.FileIO(self.path, mode)))
IOError: [Errno 2] No such file or directory: '/Users/hello/dblp/data/processed/filtered-csv/venue-1990-1990.csv'

Many thanks in advance.

**Comment by titaniumrain** [comment]
I can confirm it is a legacy issue. Newly committed code actually resolves this issue. 

Many thanks.

**Comment by macks22** [comment]
@titaniumrain I'm glad the issue is resolved. Please let me know if you have any further issues, and I will seek to address them as quickly as possible. Also, feel free to put in a PR if you make any modifications you believe would be useful to others. Thanks!
