### ISSUE TITLE
RuntimeError: Unfulfilled dependency at run time:

### ISSUE THREAD

**Issue by VANKINEENITAWRUN** [macks22/dblp#22]
Link to Log [file](https://pastebin.com/fZRvGhMu), running as per Readme getting this error.

**Comment by macks22** [comment]
That link goes back to github and there is no log there. Can you update the issue with the full log instead?

**Comment by VANKINEENITAWRUN** [comment]
@macks22 I got it fixed but Getting new Error, [link](https://pastebin.com/GxLRVjKq) to the Log. could you please help with this.? and only the authors.csv is getting created. papers.csv and refs.csv are created but only of 100 bytes. rest aren't created.
I have run the code with python2.
